/**
 * FROZEN CONTRACT — Team 2, AI Incident & Log Triage.
 *
 * Single source of truth for every branch (backend / frontend / mobile).
 * Copy this file verbatim into each app. Do NOT redefine these shapes locally,
 * and do NOT edit this file from an app branch — if the API disagrees with the
 * contract, the API is wrong.
 */

export type Severity = 'Critical' | 'High' | 'Medium' | 'Low';
export type Status = 'New' | 'Investigating' | 'Resolved';

export const SEVERITIES: Severity[] = ['Critical', 'High', 'Medium', 'Low'];
export const STATUSES: Status[] = ['New', 'Investigating', 'Resolved'];

/** Rank for sorting — higher is more urgent. */
export const SEVERITY_RANK: Record<Severity, number> = {
  Critical: 4,
  High: 3,
  Medium: 2,
  Low: 1,
};

export interface User {
  id: string;
  name: string;
  email: string;
}

export interface Incident {
  id: string;
  /** Stable hash of the normalized message — identical logs re-ingest into the same incident. */
  fingerprint: string;
  title: string;
  summary: string;
  severity: Severity;
  status: Status;
  rootCause: string;
  remediation: string;
  /** 0..1 */
  confidence: number;
  /** 0..1 — share of member entries matching the group's modal normalized message. */
  similarity: number;
  occurrences: number;
  /** ISO 8601 */
  firstSeen: string;
  /** ISO 8601 */
  lastSeen: string;
  /** Most frequent contributing module, e.g. "src/services/integrations/sterling-service.ts" */
  module: string;
  /** Every module that produced an entry in this incident. */
  modules: string[];
  /** e.g. "SterlingNotFound", "GeneralError", or null when the log carried no code. */
  code: string | null;
  acknowledged: boolean;
  assignee: Pick<User, 'id' | 'name'> | null;
}

export interface LogEntry {
  id: string;
  incidentId: string;
  /** ISO 8601 */
  timestamp: string;
  level: string;
  message: string;
  code: string | null;
  module: string;
  stack: string;
}

export type ActivityType = 'status' | 'note' | 'assign' | 'ack';

export interface Activity {
  id: string;
  incidentId: string;
  /** ISO 8601 */
  at: string;
  actor: string;
  type: ActivityType;
  from?: string;
  to?: string;
  body?: string;
}

export interface IncidentDetail extends Incident {
  entries: LogEntry[];
  history: Activity[];
}

export interface Stats {
  total: number;
  bySeverity: Record<Severity, number>;
  byStatus: Record<Status, number>;
  topIncidents: { id: string; title: string; occurrences: number }[];
  /** date is YYYY-MM-DD */
  trend: { date: string; count: number }[];
}

export type SortField = 'severity' | 'occurrences' | 'lastSeen';
export type SortOrder = 'asc' | 'desc';

export interface IncidentQuery {
  q?: string;
  /** comma-separated on the wire */
  severity?: Severity[];
  status?: Status[];
  module?: string;
  /** YYYY-MM-DD */
  from?: string;
  to?: string;
  sort?: SortField;
  order?: SortOrder;
}

export interface IncidentListResponse {
  items: Incident[];
  total: number;
}

export type JobStatus = 'queued' | 'parsing' | 'analyzing' | 'done' | 'failed';

export interface UploadJob {
  jobId: string;
  status: JobStatus;
  /** 0..100 */
  progress: number;
  parsed: number;
  grouped: number;
  error: string | null;
}

export interface ApiError {
  error: {
    code:
      | 'UNAUTHORIZED'
      | 'NOT_FOUND'
      | 'UNSUPPORTED_LOG_FORMAT'
      | 'VALIDATION_ERROR'
      | 'INTERNAL';
    message: string;
  };
}
